[assembly: ComVisible(false)]
[assembly: InternalsVisibleTo("Brows.IPC.Host")]
[assembly: InternalsVisibleTo("Brows.IPC.Host.Tests")]
[assembly: InternalsVisibleTo("Brows.IPC.Host.Tests.Program")]
[assembly: InternalsVisibleTo("Brows.IPC.Tests")]
